#!/bin/sh -x

export ANDROID_MAJOR_VERSION=q
export CROSS_COMPILE=~/Android/Sdk/ndk-bundle-r18b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-

make ARCH=arm64 exynos9820-beyondx_caliban_defconfig
make mrproper
make exynos9820-beyondx_caliban_defconfig
make -j$(nproc)
