#!/bin/sh -x

export ANDROID_MAJOR_VERSION=p

cp -p ./arch/arm64/boot/dts/exynos/Makefile-g977b ./arch/arm64/boot/dts/exynos/Makefile
make mrproper
make ARCH=arm64 exynos9820-beyondx_caliban_defconfig
make -j$(nproc) ARCH=arm64
